export const CONFIG = {
  http: {
    userAgent:
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
    timeout: 60000,
    retries: 3,
    retryDelay: 800,
    retryStatusCodes: [429, 500, 502, 503, 504],
  },

  rss: {
    defaultOpmlPath: './feeds/follow.opml',
    maxConcurrency: 20,
    feedTimeout: 60000,
    replacements: {
      'https://rsshub.app/infoq/recommend': 'https://www.infoq.cn/feed',
      'https://rsshub.app/huggingface/blog-zh': 'https://huggingface.co/blog/feed.xml',
      'https://rsshub.app/readhub/daily': 'https://readhub.cn/rss',
      'https://rsshub.app/36kr/hot-list': 'https://36kr.com/feed',
      'https://rsshub.app/sspai/index': 'https://sspai.com/feed',
      'https://rsshub.app/sspai/matrix': 'https://sspai.com/feed',
      'https://rsshub.app/meituan/tech': 'https://tech.meituan.com/feed',
      'https://mjg59.dreamwidth.org/data/rss': 'http://mjg59.dreamwidth.org/data/rss',
    } as Record<string, string>,
    skipPrefixes: [
      'https://rsshub.app/telegram/channel/',
      'https://rsshub.app/jike/',
      'https://rsshub.app/bilibili/',
      'https://rsshub.app/zhihu/',
      'https://rsshub.app/xiaoyuzhou/podcast/',
      'https://rsshub.app/xyzrank',
      'https://rsshub.app/mittrchina/hot',
      'https://wechat2rss.bestblogs.dev/',
      'https://werss.bestblogs.dev/',
      'http://47.122.94.119:18080/',
    ],
    skipExact: new Set([
      'https://rachelbythebay.com/w/atom.xml',
      'https://flak.tedunangst.com/rss',
    ]),
  },

  waytoagi: {
    defaultUrl:
      'https://waytoagi.feishu.cn/wiki/QPe5w5g7UisbEkkow8XcDmOpn8e?fromScene=spaceOverview',
    historyFallback: 'https://waytoagi.feishu.cn/wiki/FjiOwWp2giA7hRk6jjfcPioCnAc',
  },

  timezone: 'Asia/Shanghai',

  filter: {
    aiKeywords: [
      'aigc',
      'llm',
      'gpt',
      'claude',
      'gemini',
      'deepseek',
      'openai',
      'anthropic',
      'hugging face',
      'transformer',
      'prompt',
      'diffusion',
      'agent',
      '多模态',
      '大模型',
      '模型',
      '人工智能',
      '机器学习',
      '深度学习',
      '智能体',
      '算力',
      '推理',
      '微调',
    ],
    techKeywords: [
      'robot',
      'robotics',
      'embodied',
      'autonomous',
      'vision',
      'chip',
      'semiconductor',
      'cuda',
      'npu',
      'gpu',
      'cloud',
      'developer',
      '开源',
      '技术',
      '编程',
      '软件',
      '芯片',
      '机器人',
      '具身',
    ],
    // ===== 素心拾穗扩展关键词 =====
    // 认知/成长类
    cognitionKeywords: [
      '认知',
      '思维模型',
      '心智模型',
      '元认知',
      '第一性原理',
      '复盘',
      '刻意练习',
      '深度思考',
      '批判性思维',
      '成长',
      '自我提升',
      '终身学习',
      '读书',
      '阅读',
      '写作',
      '输出',
      '知识管理',
      '学习方法',
    ],
    // 个人IP/自媒体类
    ipKeywords: [
      '个人IP',
      '个人品牌',
      '自媒体',
      '内容创作',
      '视频号',
      '公众号',
      '创作者',
      '博主',
      '粉丝',
      '流量',
      '选题',
      '口播',
      '短视频',
      '内容营销',
    ],
    // 变现/商业类
    monetizeKeywords: [
      '变现',
      '赚钱',
      '副业',
      '收入',
      '商业模式',
      '橱窗带货',
      '知识付费',
      '一人公司',
      '独立开发者',
      '自由职业',
      '数字游民',
      '被动收入',
      '财务自由',
    ],
    // 回乡/乡村创业类
    ruralKeywords: [
      '回乡',
      '返乡',
      '农村',
      '乡村',
      '县城',
      '小城市',
      '新农人',
      '田园',
      '乡土',
      '家乡',
      '老家',
    ],
    // 情感/陪伴/情绪价值类
    emotionKeywords: [
      '情感',
      '情绪',
      '陪伴',
      '治愈',
      '共情',
      '倾听',
      '树洞',
      '情绪价值',
      '孤独',
      '归属感',
      '内耗',
      '自愈',
      '疗愈',
      '温暖',
      '独居',
      '慢生活',
      'vlog日常',
      '碎碎念',
      '烟火气',
      '人情味',
      // 心理/情绪/关系类（补充）
      '心理',
      '心理学',
      '焦虑',
      '抑郁',
      '压力',
      '恋爱',
      '爱情',
      '婚姻',
      '亲密关系',
      '关系',
      '分手',
      '择偶',
      '创伤',
      '自我',
      '安全感',
      '幸福',
      '幸福力',
      '心理健康',
      '心理成长',
      '情绪管理',
      // 人文/生活观察类（人物/三联风格）
      '人生',
      '生活',
      '家乡',
      '故乡',
      '妈妈',
      '母亲',
      '父亲',
      '亲情',
      '家人',
      '家庭',
      '中年',
      '老年',
      '年龄',
      '成长故事',
      '普通人',
      '人生选择',
      '人生意义',
      '日子',
      '烟火',
    ],

    // ===== 人文/思想/文学 英文关键词（2026-10-07 新增，配套英文人文源）=====
    // 用途：aeon.co / bigthink.com / theatlantic.com / electricliterature.com / newyorker.com
    // 注：匹配方式是子串包含（toLowerCase().includes），故刻意避开 art/work/home/land/mind/class
    //     这类会误召（article/start/party/framework）的短词，只放 5 字以上或语义明确的词。
    humanitiesKeywords: [
      // 阅读 / 写作 / 文学
      'reading', 'books', 'book review', 'literature', 'literary', 'essay',
      'memoir', 'novel', 'poetry', 'fiction', 'writer', 'writing', 'prose',
      // 思想 / 哲学 / 注意力
      'philosophy', 'philosopher', 'attention', 'contemplation', 'consciousness',
      'wisdom', 'intellectual', 'meaning of', 'search for meaning',
      // 情绪 / 关系 / 生命历程
      'loneliness', 'solitude', 'grief', 'mourning', 'longing', 'belonging',
      'intimacy', 'friendship', 'motherhood', 'fatherhood', 'marriage',
      'childhood', 'memory', 'aging',
      // 地方 / 乡村 / 土地
      'rural', 'village', 'countryside', 'hometown', 'small town',
      'farming', 'farmer', 'provincial',
      // 创作 / 手艺 / 文化
      'creativity', 'craft', 'storytelling', 'culture',
      // 社会观察
      'inequality', 'gender', 'women', 'community', 'working class',
    ],

    noiseKeywords: ['娱乐', '明星', '八卦', '足球', '篮球', '彩票', '旅游', '美食'],
    commerceNoiseKeywords: [
      '��宝',
      '天猫',
      '京东',
      '拼多多',
      '券后',
      '热销总榜',
      '促销',
      '优惠',
      '补贴',
      '下单',
      '首发价',
    ],
    tophubAllowKeywords: [
      'readhub · ai',
      'hacker news',
      'github',
      'product hunt',
      'v2ex',
      '少数派',
      'infoq',
      '36氪',
      '机器之心',
      '量子位',
      '科技',
      '人工智能',
      '机器人',
      '具身',
      '开源',
      '认知',
      '成长',
      '自媒体',
      '创业',
      '副业',
    ],
    tophubBlockKeywords: [
      '热销总榜',
      '淘宝',
      '天猫',
      '京东',
      '拼多多',
      '抖音',
      '快手',
      '微博',
      '小红书',
    ],
    enSignalPattern:
      /(?<![a-z0-9])(ai|aigc|llm|gpt|openai|anthropic|deepseek|gemini|claude|robot|robotics|embodied|autonomous|machine learning|artificial intelligence|transformer|diffusion|agent)(?![a-z0-9])/i,
  },
};
