export const CONFIG = {
  http: {
    userAgent:
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
    timeout: 60000,
    retries: 3,
    retryDelay: 800,
    retryStatusCodes: [429, 500, 502, 503, 504],
  },

  rss: {
    defaultOpmlPath: './feeds/follow.opml',
    maxConcurrency: 20,
    feedTimeout: 60000,
    replacements: {
      'https://rsshub.app/infoq/recommend': 'https://www.infoq.cn/feed',
      'https://rsshub.app/huggingface/blog-zh': 'https://huggingface.co/blog/feed.xml',
      'https://rsshub.app/readhub/daily': 'https://readhub.cn/rss',
      'https://rsshub.app/36kr/hot-list': 'https://36kr.com/feed',
      'https://rsshub.app/sspai/index': 'https://sspai.com/feed',
      'https://rsshub.app/sspai/matrix': 'https://sspai.com/feed',
      'https://rsshub.app/meituan/tech': 'https://tech.meituan.com/feed',
      'https://mjg59.dreamwidth.org/data/rss': 'http://mjg59.dreamwidth.org/data/rss',
    } as Record<string, string>,
    skipPrefixes: [
      'https://rsshub.app/telegram/channel/',
      'https://rsshub.app/jike/',
      'https://rsshub.app/bilibili/',
      'https://rsshub.app/zhihu/',
      'https://rsshub.app/xiaoyuzhou/podcast/',
      'https://rsshub.app/xyzrank',
      'https://rsshub.app/mittrchina/hot',
      'https://wechat2rss.bestblogs.dev/',
      'https://werss.bestblogs.dev/',
      'http://47.122.94.119:18080/',
    ],
    skipExact: new Set([
      'https://rachelbythebay.com/w/atom.xml',
      'https://flak.tedunangst.com/rss',
    ]),
  },

  waytoagi: {
    defaultUrl:
      'https://waytoagi.feishu.cn/wiki/QPe5w5g7UisbEkkow8XcDmOpn8e?fromScene=spaceOverview',
    historyFallback: 'https://waytoagi.feishu.cn/wiki/FjiOwWp2giA7hRk6jjfcPioCnAc',
  },

  timezone: 'Asia/Shanghai',

  filter: {
    aiKeywords: [
      'aigc',
      'llm',
      'gpt',
      'claude',
      'gemini',
      'deepseek',
      'openai',
      'anthropic',
      'hugging face',
      'transformer',
      'prompt',
      'diffusion',
      'agent',
      '多模态',
      '大模型',
      '模型',
      '人工智能',
      '机器学习',
      '深度学习',
      '智能体',
      '算力',
      '推理',
      '微调',
    ],
    techKeywords: [
      'robot',
      'robotics',
      'embodied',
      'autonomous',
      'vision',
      'chip',
      'semiconductor',
      'cuda',
      'npu',
      'gpu',
      'cloud',
      'developer',
      '开源',
      '技术',
      '编程',
      '软件',
      '芯片',
      '机器人',
      '具身',
    ],
    // ===== 素心拾穗扩展关键词 =====
    // 认知/成长类
    cognitionKeywords: [
      '认知',
      '思维模型',
      '心智模型',
      '元认知',
      '第一性原理',
      '复盘',
      '刻意练习',
      '深度思考',
      '批判性思维',
      '成长',
      '自我提升',
      '终身学习',
      '读书',
      '阅读',
      '写作',
      '输出',
      '知识管理',
      '学习方法',
    ],
    // 个人IP/自媒体类
    ipKeywords: [
      '个人IP',
      '个人品牌',
      '自媒体',
      '内容创作',
      '视频号',
      '公众号',
      '创作者',
      '博主',
      '粉丝',
      '流量',
      '选题',
      '口播',
      '短视频',
      '内容营销',
    ],
    // 变现/商业类
    monetizeKeywords: [
      '变现',
      '赚钱',
      '副业',
      '收入',
      '商业模式',
      '橱窗带货',
      '知识付费',
      '一人公司',
      '独立开发者',
      '自由职业',
      '数字游民',
      '被动收入',
      '财务自由',
    ],
    // 回乡/乡村创业类
    ruralKeywords: [
      '回乡',
      '返乡',
      '农村',
      '乡村',
      '县城',
      '小城市',
      '新农人',
      '田园',
      '乡土',
      '家乡',
      '老家',
    ],

    noiseKeywords: ['娱乐', '明星', '八卦', '足球', '篮球', '彩票', '情感', '旅游', '美食'],
    commerceNoiseKeywords: [
      '��宝',
      '天猫',
      '京东',
      '拼多多',
      '券后',
      '热销总榜',
      '促销',
      '优惠',
      '补贴',
      '下单',
      '首发价',
    ],
    tophubAllowKeywords: [
      'readhub · ai',
      'hacker news',
      'github',
      'product hunt',
      'v2ex',
      '少数派',
      'infoq',
      '36氪',
      '机器之心',
      '量子位',
      '科技',
      '人工智能',
      '机器人',
      '具身',
      '开源',
      '认知',
      '成长',
      '自媒体',
      '创业',
      '副业',
    ],
    tophubBlockKeywords: [
      '热销总榜',
      '淘宝',
      '天猫',
      '京东',
      '拼多多',
      '抖音',
      '快手',
      '微博',
      '小红书',
    ],
    enSignalPattern:
      /(?<![a-z0-9])(ai|aigc|llm|gpt|openai|anthropic|deepseek|gemini|claude|robot|robotics|embodied|autonomous|machine learning|artificial intelligence|transformer|diffusion|agent)(?![a-z0-9])/i,
  },
};
